import type { Metadata } from "next";
import css from "./Home.module.css";

export const metadata: Metadata = {
  title: "not-found Note",
  description: "NoteHub - your personal note-taking app",
  openGraph : {
    title: 'NoteHub - Page Not Found',
    description: 'Generated by create note',
    url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
    images: [
      {
        url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
        width: 1200,
        height: 630,
        alt: 'NoteHub',
      },
    ],
  },
};


export default function NotFoundPage() {
  return (
    <div className={css.container}>
      <h1 className={css.title}>404 - Page not found</h1>
      <p className={css.description}>Sorry, the page you are looking for does not exist.</p>
    </div>
  );
}
